### ISSUE TITLE
Testing on MPI-INF-3DHP

### ISSUE THREAD

**Issue by nies14** [YxZhxn/Ray3D#2]
Hi, thanks for the great work. Could you please say how can I train & test MPI-INF-3DHP using 14 joint skeleton structure? And, do I need to prepare seperately 'data_2d_3dhp_gt.npz' which has only 14 joints or the one you shared is gonna work?

**Comment by YxZhxn** [comment]
Hi, you can launch training and testing using 14-joint skeleton directly with the npz files that we provided. Just use 'universal' instead of 'gt' for 'KEYPOINTS' in data_config, then you are good to go. 

https://github.com/YxZhxn/Ray3D/blob/cfcbd96d0dac91d46c0333ef2a290af9f29fad85/cfg/cfg_ray3d_h36m_cross_stage1.py#L7

**Comment by YxZhxn** [comment]
> Hi, you can launch training and testing using 14-joint skeleton directly with the npz files that we provided. Just use 'universal' instead of 'gt' for 'KEYPOINTS' in data_config, then you are good to go.
> 
> https://github.com/YxZhxn/Ray3D/blob/cfcbd96d0dac91d46c0333ef2a290af9f29fad85/cfg/cfg_ray3d_h36m_cross_stage1.py#L7

Also, you have to change number of keypoints to 14 explicitly here
https://github.com/YxZhxn/Ray3D/blob/cfcbd96d0dac91d46c0333ef2a290af9f29fad85/cfg/cfg_ray3d_h36m_cross_stage1.py#L64
