### ISSUE TITLE
3dhp 2d keypoints

### ISSUE THREAD

**Issue by alecda573** [YxZhxn/Ray3D#4]
Firstly, this is really interesting work, kuddos! 
can you please explain what 
'WORLD_3D_GT_EVAL'
represents in the config files?
Also, do you all convert 3d coordinates to meters? 
If so can you point me to this? 

Lastly, if I set 
'RAY_ENCODING'
to False, in the config filethis will return screen normalized 2d keypoints and 3d keypoints in the  camera reference frame that are root centered correct?

**Comment by YxZhxn** [comment]
Hi Alecda.
1. We originally use WORLD_3D_GT_EVAL to separate fully supervised learning and weakly supervised learning. Since our method is designed in fully supervised manner now, this parameter is set as true in all config files.
2. You're right. Before training and testing, all 3d coordinates are converted to meters. 3d coordinates in all .npz files are measured in meter unit.
3. If both RAY_ENCODING and INTRINSIC_ENCODING (actually this parameter should be renamed as INTRINSIC_DECODING) are false, screen normalized 2d keypoints and absolute 3d keypoints in the camera reference frame will be returned. It will be transformed to root relative pose during training and testing
https://github.com/YxZhxn/Ray3D/blob/cfcbd96d0dac91d46c0333ef2a290af9f29fad85/lib/train_val/trainer.py#L92
https://github.com/YxZhxn/Ray3D/blob/cfcbd96d0dac91d46c0333ef2a290af9f29fad85/lib/train_val/trainer.py#L196
If RAY_ENCODING is false and INTRINSIC_ENCODING is true, 2d keypoints will decouple the focal length and camera centers. You can check the logic here: 
https://github.com/YxZhxn/Ray3D/blob/cfcbd96d0dac91d46c0333ef2a290af9f29fad85/lib/dataset/__init__.py#L23-L42
